### PR TITLE
fix(for-react): incorrect destruction logic in toolbar

### LINKED ISSUE #722: for react 的 Toolbar 清理逻辑错误造成 rerender 时 Toolbar 意外销毁
## bug 描述

Toolbar effect 依赖了 `defaultConfig`，当 setHtml 时，普通对象的 `defaultConfig` 重新创建会使 effect 重新执行：清理 Toolbar，但是由于 `data-w-e-toolbar` 属性依然存在于元素上，提前 return 并没有重新创建，因此只是单纯的销毁了 Toolbar。

这个问题在 `@wangeditor-next/editor` 5.6.5 下并未发生，应该是后续版本迭代造成的 for react 和 editor 不匹配

## 你预期的样子是？

Toolbar 应该只在销毁时执行 destory

## 系统和浏览器及版本号

- 操作系统 Windows
- 浏览器和版本 Chrome 142.0.7444.59

## wangEditor-next 版本

- @wangeditor-next/editor 5.6.47
- @wangeditor-next/editor-for-react 1.0.10

## demo 能否复现该 bug ？

能

- demo https://wangeditor-next.github.io/docs/en/guide/for-frame#react

## 在线 demo

[StackBlitz Reproduce](https://stackblitz.com/edit/vitejs-vite-qx75brsr)

## 最小成本的复现步骤

- 创建一个 react 项目
- 安装 `@wangeditor-next/editor`  `@wangeditor-next/editor-for-react`
- 复制文档中 react 的 demo
- 启动项目并观察 Toolbar

### PR DESCRIPTION
**Pull request by json-q**
## Implementation Approach

当执行 destroy 时，需要将附加到元素上的 `data-w-e-toolbar` 移除，这样不会影响后续的条件判断

## Checklist
- [x] I have created a [changeset](https://github.com/changesets/changesets) for this PR if necessary.
- [x] My changes do not break the library.
- [x] I have added tests where applicable.
- [x] I have followed the project guidelines.
- [x] I have fixed any lint issues.

## Related Issues

fix: https://github.com/wangeditor-next/wangEditor-next/issues/722

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed toolbar cleanup to prevent lingering toolbar instances and residual toolbar artifacts when closing or unmounting the editor, improving stability.

* **Refactor**
  * Simplified toolbar lifecycle handling so the toolbar persists across renders and is consistently destroyed only on unmount, reducing unexpected behavior during re-renders.

### CODE REVIEW

File: packages/editor-for-react/src/components/Toolbar.tsx [hunk 1]
```diff
@@ -19,26 +19,33 @@ function ToolbarComponent(props: IProps) {
...
+    }
+  }
 
   useEffect(() => {
-    if (ref.current == null) { return }
-    if (editor == null) { return }
+    if (ref.current == null || editor == null) {
+      return destroyToolbar()
+    }
     if (ref.current?.getAttribute('data-w-e-toolbar')) { return }
```
Comment (json-q) [inline packages/editor-for-react/src/components/Toolbar.tsx]: 这个属性的判断现在会造成 defaultConfig 和 mode 变化时无法更新，我回头补一下

**Comment by json-q** [comment]
想复杂了，主要就是 atrribute 在执行 destroy 后依然存在导致现有的逻辑不通
不知道这个改动会不会造成 break change，如果行为要统一的话就要去改 core 了
 @cycleccc cc
